[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "mm-utils"
dynamic = ["version"]
description = "Common utils and logging configurations for ManoMano Python projects"
authors = [
    {name = "Gabriel Dugny", email = "gabriel.dugny@manomano.com"},
    {name = "Elie Bleton", email = "elie.bleton@manomano.com"},
    {name = "Jonathan Gallon", email = "jonathan.gallon@manomano.com"},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}


[project.optional-dependencies]
pygit2 = [
    "pygit2>=1.11.1",
]
loguru = [
    "loguru>=0.6.0",
]

[tool.hatch.version]
path = "mm_utils/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=mm_utils --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[tool.hatch.envs.test.matrix]]
python = [  "310", "311"]


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
[tool.coverage.run]
branch = true
parallel = true
omit = [
  "mm_utils/__about__.py",
  "tests/*",
  "__pypackages__",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.pdm]
version = { source = "file", path = "mm_utils/__version__.py" }
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.2.0",
    "isort>=5.11.1",
    "black>=22.12.0",
    "mypy>=0.991",
    "pylint>=2.15.8",
]
doc = [
    "mkdocs>=1.4.2",
    "mkdocs-material>=8.5.11",
]



[tool.black]
line-length = 140
target-version = ['py310']

[tool.isort]
profile = "black"
py_version = 310
line_length = 140
wrap_length = 140

[tool.pylint.MASTER]
py-version = "3.10"
ignore = ['__pypackages__', '.git', 'packages']

[tool.pylint.FORMAT]
max-line-length = 140
